receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:55679

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5000
    sampling_thereafter: 10000
  otlphttp/grafana:
    endpoint: https://otlp-gateway-prod-us-central-0.grafana.net/otlp
    headers: 
      authorization: ${env:GRAFANA_AUTHORIZATION}
  otlp/jaeger:
    endpoint: localhost:4317
    tls:
      insecure: true
  otlphttp/dynatrace:
    endpoint: https://nnr98912.live.dynatrace.com/api/v2/otlp
    headers:
      Authorization: ${env:DYNATRACE_TOKEN}
extensions:
  health_check:

service:
  telemetry:
    logs:
      level: info
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/grafana]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/dynatrace]