{
 "title": "Demo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(system_cpu_usage{job=\"cart-service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_memory_used{job=\"cart-service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Http request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_count{job=\"cart-service\"}[5m])) by (method, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_count{job=\"cart-service\", status=~\"5.*\"}[5m])) by (method, uri)",
     "legendFormat": "5xx {{method}} {{uri}}"
    },
    {
     "expr": "sum(rate(http_server_requests_count{job=\"cart-service\", status=~\"4.*\"}[5m])) by (method, uri)",
     "legendFormat": "4xx {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_bucket{job=\"cart-service\"}[5m])) by(method, status, uri)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}